-- 코드를 작성해주세요
SELECT I.ITEM_ID, I.ITEM_NAME, I.RARITY
FROM ITEM_INFO I
WHERE I.ITEM_ID IN 
(
    SELECT T.ITEM_ID
    FROM ITEM_INFO I JOIN ITEM_TREE T ON (I.ITEM_ID = T.PARENT_ITEM_ID)
    WHERE I.RARITY = 'RARE'
)
ORDER BY I.ITEM_ID DESC